### ISSUE TITLE
Release version-1

### ISSUE THREAD

**Issue by roll** [frictionlessdata/goodtables-py#105]
# Overview

Tracking issue for https://github.com/frictionlessdata/goodtables-py/milestone/9

# Tasks

- [x] update implementation
- [x] release ALPHA
---
- [x] provide visual separation for values inside error messages (add quotes doing spec template formatting) - MOVED #163
- [x] expose package version
- [x] remove `alpha` from dependencies
- [x] remove deprecated code
- [x] improve test coverage - MOVED #127 
- [x] set coverage threshold in coverals to 90% - MOVED #127
- [x] DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
- [x] Readme improvements:
  - [x] highlight in docs that schema checks is not enabled by default
  - [x] Couple of simple library examples at the top - the obvious stuff
    - [x] Validate data in a datapackage (all or just one resource)
    - [x] Validate data in a CSV with and without a JSON Table Schema
  - [x] Explain conceptually the two types of checking that the library does: Structure and Schema
    - [x] Give a CLI datapackage example
    - [x] Explain what `infer-fields` does ...
- [ ] release

**Comment by pwalsh** [comment]
@roll looks like this is now done!

**Comment by roll** [comment]
@pwalsh 
But we still on alpha. Let's track here final release (as for the other libs).
