### ISSUE TITLE
Rebase on specs-v1 implementations

### ISSUE THREAD

**Issue by roll** [frictionlessdata/goodtables-py#174]
# Overview

We have to migrate to `tableschema-v1` and `datapackage-v1`

# Tasks

- [x] update dependencies
- [x] use `Schema(strict=False)`  in `table` preset (see https://github.com/frictionlessdata/tableschema-py/issues/113)
- [x] use `resource.tabular` in `datapackage` preset
- [x] ensure we support `header=False` from CSV dialect for datapackages
- [x] ensure all required changes are applied
