### ISSUE TITLE
Add warnings system?

### ISSUE THREAD

**Issue by roll** [frictionlessdata/goodtables-py#184]
# Overview

It's up on the air related to issues:
- #157
- https://github.com/frictionlessdata/data-quality-spec/issues/11

It should replace dataset level errors and provide ability to do other types of feedback to users inside the goodtables report (not failing with an exception).

It should be like (a `report` part example):

```json
{
  "warninigs": [
    "Invalid datapackage property #1",
    "Invalid datapackage property #2",
    "File <name> inspection has stopped because of error limit",
  ]
}
```

# Tasks

- [ ] implement warning system instead of dataset level errors
- [ ] make presets emit warnings instead of errors
- [ ] add warnings about hitting limits (table, error etc)
