### ISSUE TITLE
Implement contrib.checks

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/goodtables-py#191]
# Description

Users and potential users are consistently asking for more complex checks. 

We've always supported extensibility in checks, and imagined the type of things that could be implemented for more involved data integrity validation. However, it is clear that the value of goodtables would greatly increase if some such checks were built in to the library, not in the least so that they would eventually be accessible via [goodtables.io](https://goodtables.io).

I recommend that such checks should be shipped as a `contrib` module, in the spirit of [Django Contrib](https://github.com/django/django/tree/master/django/contrib). We could further namespace into groups, for discoverability reasons, but probably not necessary now.

Common requests:

- Check that a column of integers increments
- Declare constraint logic across multiple columns
- Check variation in a column from a mean

# Tasks

- [x] Agree on a design for a contrib module for checks
- [x] Decide on a set of initial checks we can ship based on current needs and feedback
- [x] Implement decided checks

**Comment by pwalsh** [comment]
also see link to probes in https://github.com/frictionlessdata/goodtables-py/issues/10

**Comment by pwalsh** [comment]
I think we will move on a `contrib.checks` module sooner, rather than later. We've had many signals in recent months on the utility of this, including from pilot partners.

Here is another of checks that a pilot partner has identified, with some comments from me in `[]`:

- Check for administrative variables that should not be in the data [means scanning cells against a black list of terms]
- Check for duplicate variables [we do duplicate rows, this is the same, but duplicates in columns, and therefore supported directly with `constraints.unique: true`]
- Check out of range values according to the code book [classic case. can be done based on hard range limits, or % of deviation, or some other ways I suppose]
- Look for any missing values not defined in code book [check values against a passed lookup table - similar implementation to the blacklist]
- Look for truncated numeric values or string variables [probably supported with core checks]
- Check variable and value labels are complete and make sense/are not truncated [need clarity]
- Sometimes logical checks: - make sure men or 90 years old women have not had babies! (usually done thoroughly by the survey owner) [checks across fields is coming up a lot. I guess what we need is an abstract to apply other checks across multiple fields, combined with IF OR and AND statements]
- Check derived variables make sense according to documentation [not clear]
- Disclosure risk (small frequency counts, outliers) [can be down with very basic statistical analysis over all columns]

**Comment by roll** [comment]
@pwalsh 
@amercader 
@danfowler 
So which checks we're going to implement on the first iteration?
- easy choice to be the first check is `sequential-column` (help with name)
- ???

**Comment by roll** [comment]
Good source of an inspiration - https://github.com/dataproofer/Dataproofer#test-suites
