### ISSUE TITLE
Integrate data quality cli into a contrib module

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/goodtables-py#194]
# Description

[Data Quality CLI](https://github.com/frictionlessdata/data-quality-cli) is essentially a wrapper around goodtables, for generating timeline reports on the data quality of a collection of datasets. We want to be able to ship this as a contrib module for goodtables because:

1. It does not need to be standalone, and some parts are useful outside of the Data Quality CLI context (e.g.: the CKAN Generator)
2. We can use goodtables.io to run the same tasks as Data Quality CLI, and build on this to get [Data Quality Dashboards](https://github.com/frictionlessdata/data-quality-dashboard) for data sources in goodtables.io

# Tasks

- [ ] Have a `goodtables-contrib` module ( also see https://github.com/frictionlessdata/goodtables-py/issues/191 )
- [ ] Have contrib preset for CKAN, based on the [CKAN Generator in Data Quality CLI](https://github.com/frictionlessdata/data-quality-cli/blob/master/data_quality/generators/ckan.py)
- [ ] Rewrite the [`Aggregator`](https://github.com/frictionlessdata/data-quality-cli/blob/master/data_quality/tasks/aggregate.py), possibly to just run on output reports, or some other integration with how v1 goodtables works
- [ ] Check about how rest of plumbing works (dq config etc) and see how to best port this
- [ ] Move the DB to SQL backend??

# Goals

- Data Quality Dashboard for any (potential) goodtables.io data source

**Comment by pwalsh** [comment]
@roll @georgiana-b any thoughts?

**Comment by roll** [comment]
@pwalsh I'll dive in it today

**Comment by roll** [comment]
I still have more high-level understanding of how `data-quality-cli/dashboard` works but could contribute a few thoughts:
- merging `data-quality-cli` and `goodtables-py` we could bloat `goodtables-py` to much. Generating data quality datapackage is relevant but still I think distinct task than generating a goodtables report. It's like parallel readme, parallel cli, configuration files, probably db dependencies etc. It's a tempting idea to have all this stuff behind `goodtables` cli command but we should think twice to do not break `do one thing and do it well` thing (which strictly related to maintainability)
- if not merging we still could put as many as possibly code to `goodtables.contrib` (presets, checks etc). Other part of `data-quality-cli` seems very closely coupled to Data Quality Dashboard (only one user of dq-cli ouput?). For example Data Quality Dashboard could provide it's own cli which uses `goodtables-py`  json output. So it will be two massive projects `goodtables-py` and `data-quality-dashboard`. Also just got a feeling - isn't things which data-quality-cli does nowadays used to be done via `datapackage-pipelines`?

**Comment by pwalsh** [comment]
Some points, some repeated:

- It does not have to bloat goodtables at all as an optional contrib module.
- Some aspects of this (like the CKAN preset) are generally useful for goodtables use, and not specific to the DQCLI.
- Most of the configuration aspects of DQCLI can be reduced to a couple of keyword arguments - it is just cruft from the historical and iterative process of building it.
- There is no dependency on the dashboard. DQ CLI is essentially a time series over multiple GT reports, for a collection of files. This is generally useful, the dashboard is just the first prototype we made for showing such historical/change info. Such info could also be directly integrated into gtio, for example
