### ISSUE TITLE
Finalize custom presets/checks API and checks parameter for validate function

### ISSUE THREAD

**Issue by roll** [frictionlessdata/goodtables-py#198]
# Overview

For `v1` custom presets and checks are provisional API. As a part of work on `contrib.checks` (#191) we tests all edge cases and finalize those APIs. Also we have make a final decision on how `validate(checks=...)` parameter works. We should take into account that it also should be easy-to-use in CLI and `goodtables.yml`.

# Tasks

- [ ] learn from all edge cases on `contrib.checks`
- [ ] handle feedback on interface provided below
- [ ] discuss `validate(checks)`
- [ ] make changes if needed
- [ ] improve documentation/tutorials

---

From @pwalsh:

Some issues I encountered using goodtables v1 pre.

1. Checks: There is no documentation, and the semantics are not clear. Example: Does `column` refer to a cell in a row, or a column of cells? It must be the former as we are streaming rows, but it is confusing because a column is not a cell.
2. Register: The `check` (and `preset`) decorators are implemented from the `register` module. This suggests that functions decorated as such may get added to a registry of checks and presets. However, we "register" custom checks and presets on the `Inspector` constructor explicitly, So it is not clear to me why we need decorators, when we can just ensure that custom presets and checks implement the signature required to be a `preset` or a `check`. As a user, it feels like extra configuration that I don't need.

**Comment by roll** [comment]
@roll:

- improved `validate(checks)` argument. Examples (will be documented as a part of #198):
  - `checks='spec'` - default, all spec checks
  - `checks='schema'` - only schema checks
  - `checks=['structure', 'extra-header', 'missing-header']` - list expanding `structure` group
  - `checks={'blank-row': False}` - cherry-pick check
  - `checks={'spec': True, 'blank-row': False}` - all spec checks but not `blank-row`
  - `checks={'schema': True, 'required-constraint': False}` - all schema checks but not `required-constraint`
  - `checks={'sequential-column': {'column': 'id'}}` - one contrib check with parameters
  - etc

---

@amercader:

I'm not totally sold on how the checks parameter is working right now TBH, there's just too many variants. For instance is this possible? checks={'sequential-column': True} If so what about parameters?

Perhaps is best to have explicit params for validate: include_checks, exclude_checks? Not sure, just wondering.

You've given more thought to this so definitely not blocking on my side.

**Comment by roll** [comment]
> checks={'sequential-column': True}
I would say that's `GoodtablesException` not related to `checks` parameter. This check requires a `column` option (we have to think how to provide this info in error message).

So related to `checks`. Yes I had a lot a thoughts on it now and on first iteration. Sadly I don't see some perfect solution esp. it should be good also for CLI and `goodtables.yml`.

For now concept that there is no defaults for `checks` parameter. So we do not excluding or including checks but we construct it from 0 initial checks:
```
spec - all
schema - spec schema
[structure, required-constraint] - structure + required
{sequential-column: {}} - only sequential column (I think that's important if user don't need spec checks)
{spec: True, sequential-column: {}} - spec with sequential column
{spec: True, missing-header: False} - spec without missing header
{schema: True, required-constraint: False} - spec schema without required constraint
```
I can't say I'm really happy with it. But at least it's based on some strong concept - you get all checks that you ask (no implicit defaults).

So having `include_checks` and `exclude_checks` I suppose means that we have all `spec` checks included by default. So have other type of problem - with individual checks: 
```
exclude_checks=spec, include_checks=sequential-column: {} - to check only sequential column
```
Doesn't seem ideal also. 

So something to think about.

**Comment by roll** [comment]
So main question I suppose should be - to include all `specs` checks by default or not..
