### ISSUE TITLE
Review the CLI API

### ISSUE THREAD

**Issue by vitorbaptista** [frictionlessdata/goodtables-py#233]
This is our current CLI help:

```
Usage: goodtables [OPTIONS] SOURCE

  https://github.com/frictionlessdata/goodtables-py#cli

Options:
  --preset TEXT
  --schema TEXT
  --checks <LAMBDA>
  --skip-checks <LAMBDA>
  --infer-schema
  --infer-fields
  --order-fields
  --error-limit INTEGER
  --table-limit INTEGER
  --row-limit INTEGER
  --json
  --version               Show the version and exit.
  --help                  Show this message and exit.
```

If you don't know what these options mean, it's not helpful

## Tasks

- [x] Validate that the parameters (e.g. `row-limit` should be greater than zero 0)
- [x] Allow reading from STDIN
- [x] Allow glob paths (https://github.com/frictionlessdata/goodtables-py/issues/229)
- [x] Review defaults (maybe we could remove the 1000 rows limit?)
- [x] Explain what goodtables does, and each of its options
- [x] Add `--quiet` option
- [x] Support short and long options (e.g. `-v` and `--verbose`)
- [ ] Consider not outputting anything when the data is valid (as is costumary in UNIX)

##  Resources

* https://zapier.com/engineering/how-to-cli/
* http://eng.localytics.com/exploring-cli-best-practices/
* http://docopt.org/
* https://softwareengineering.stackexchange.com/questions/307467/what-are-good-habits-for-designing-command-line-arguments
* http://www.catb.org/esr/writings/taoup/html/ch10s05.html
* https://medium.com/re-form/ux-for-wizards-e6ffaad577b4

**Comment by vitorbaptista** [comment]
Fixed
