### ISSUE TITLE
General goodtables-py update

### ISSUE THREAD

**Issue by roll** [frictionlessdata/goodtables-py#341]
# Overview

The `goodtables-py` library is a user of all our underlying stack and a "face" of all Python implementations. It's become slightly rusty code-wise lately because a lot of people have been working on it (including Vitor's massive changes) and it's kinda slow because it's never been optimized to be fast (our focus has always been on minimal memory consumption). For example, limited pandas-based validation around x20 faster that `goodtables-py`.

# Tasks

- [ ] clean up `inspector/validate` modules, probably updating some protocols in use (required by the next step)
- [ ] rebase on multi-processing - https://github.com/frictionlessdata/goodtables-py/issues/255
- [ ] profile/optimize parts of the stack to improve overall performance of validation
- [ ] tidy up other parts, especially re-check tests

Estimation: 5 days
